/**
 * Main Application - Alpine.js stores and initialization
 */

// Version is loaded from version.js (generated by update-version.sh)
console.log(`Flashcards App [${window.APP_VERSION || 'dev'}] - ${window.APP_BUILD_TIME || 'unknown build time'}`);

document.addEventListener('alpine:init', () => {

  /**
   * Main application store
   * Manages global state, navigation, and data
   */
  Alpine.store('app', {
    // Current view: 'home' | 'session' | 'stats' | 'settings' | 'add-deck'
    currentView: 'home',

    // Currently selected deck
    currentDeck: null,

    // All decks
    decks: [],

    // Loading state
    isLoading: false,

    // Error message
    error: null,

    // Success message
    success: null,

    /**
     * Initialize the app
     */
    init() {
      this.migrateLegacyDecks();
      this.loadDecks();
      // Background-sync all decks so new rows appear without a manual action.
      // Failures are per-deck and leave cached cards in place.
      SyncService.syncAllDecks().catch(err => console.warn('syncAllDecks failed:', err));
      console.log('Flashcards app initialized');
    },

    /**
     * One-time migration: decks that were linked via the old OAuth flow have
     * spreadsheetId but no csvUrl. Build csvUrl from spreadsheetId with gid=0.
     * If the sheet isn't public, the first fetch will fail and the user will
     * see an error on that deck — which is the intended surfacing.
     */
    migrateLegacyDecks() {
      const decks = DeckStorage.getAll();
      let migrated = 0;
      for (const deck of decks) {
        if (!deck.csvUrl && deck.spreadsheetId) {
          const gid = deck.gid || '0';
          DeckStorage.update(deck.id, {
            gid,
            csvUrl: SheetsService.buildCsvUrl(deck.spreadsheetId, gid)
          });
          migrated++;
        }
      }
      if (migrated > 0) {
        console.log(`Migrated ${migrated} legacy deck(s) to csvUrl`);
      }
    },

    /**
     * Load decks from storage
     */
    loadDecks() {
      this.decks = DeckStorage.getAll();
      // Auto-select first deck if exists and none selected
      if (this.decks.length > 0 && !this.currentDeck) {
        this.selectDeck(this.decks[0].id);
      } else if (this.currentDeck) {
        // Refresh currentDeck reference so lastSyncedAt updates propagate
        const fresh = DeckStorage.getById(this.currentDeck.id);
        if (fresh) this.currentDeck = fresh;
      }
    },

    /**
     * Select a deck
     */
    selectDeck(deckId) {
      this.currentDeck = DeckStorage.getById(deckId);
    },

    /**
     * Navigate to a view
     */
    navigate(view) {
      this.currentView = view;
      this.clearMessages();
    },

    /**
     * Set loading state
     */
    setLoading(loading) {
      this.isLoading = loading;
    },

    /**
     * Show error message
     */
    showError(message) {
      this.error = message;
      setTimeout(() => this.error = null, 5000);
    },

    /**
     * Show success message
     */
    showSuccess(message) {
      this.success = message;
      setTimeout(() => this.success = null, 3000);
    },

    /**
     * Clear all messages
     */
    clearMessages() {
      this.error = null;
      this.success = null;
    },

    /**
     * Add a deck from a pasted Google Sheets URL. Validates, test-fetches,
     * creates the deck, and runs an immediate sync.
     * @returns {Promise<{success:boolean, message:string}>}
     */
    async addDeckFromUrl(name, url) {
      const trimmedName = (name || '').trim();
      const parsed = SheetsService.parseSheetUrl(url);

      if (!trimmedName) {
        return { success: false, message: 'Please enter a deck name.' };
      }
      if (!parsed) {
        return { success: false, message: "That doesn't look like a Google Sheets URL." };
      }

      const csvUrl = SheetsService.buildCsvUrl(parsed.spreadsheetId, parsed.gid);

      this.setLoading(true);
      try {
        const result = await SheetsService.fetchCsv(csvUrl);
        if (!result.success) {
          return { success: false, message: result.error };
        }

        const deck = DeckStorage.create({
          name: trimmedName,
          spreadsheetId: parsed.spreadsheetId,
          gid: parsed.gid,
          csvUrl
        });

        const syncStats = await CardStorage.syncCards(deck.id, result.cards);
        DeckStorage.update(deck.id, { lastSyncedAt: new Date().toISOString() });

        this.loadDecks();
        this.selectDeck(deck.id);

        return {
          success: true,
          message: `Added "${trimmedName}" with ${syncStats.created} cards.`
        };
      } catch (err) {
        console.error('addDeckFromUrl error:', err);
        return { success: false, message: 'Failed to add deck: ' + err.message };
      } finally {
        this.setLoading(false);
      }
    },

    /**
     * Delete a deck (archives its cards; review history preserved in log).
     */
    deleteDeck(deckId) {
      DeckStorage.delete(deckId);
      if (this.currentDeck && this.currentDeck.id === deckId) {
        this.currentDeck = null;
      }
      this.loadDecks();
    }
  });

  /**
   * Session store
   * Manages flashcard review session state
   *
   * State machine:
   *   SHOWING_QUESTION -> (tap) -> SHOWING_ANSWER
   *   SHOWING_ANSWER -> (button click) -> FLIPPING_BACK
   *   FLIPPING_BACK -> (animation done) -> SHOWING_QUESTION (with new card)
   */
  Alpine.store('session', {
    // State: 'question' | 'answer' | 'flipping'
    state: 'question',

    // Deck currently being studied
    currentDeckId: null,

    // Current card being reviewed
    currentCard: null,

    // Next card (preloaded during flip animation)
    nextCardData: null,

    // Session start time
    sessionStartedAt: null,

    // Current card start time
    cardStartedAt: null,

    // Cards reviewed in this session
    reviewedCount: 0,

    // Correct answers in this session
    correctCount: 0,

    // Session-local retry queue: cards answered incorrectly, waiting to reappear.
    // Each entry: { cardId: string, counter: number } — counter decrements after each
    // subsequent answer; card resurfaces when counter <= 0.
    retryQueue: [],

    // Count of never-reviewed cards surfaced this session (for newCardsPerSession cap)
    newCardsSurfaced: 0,

    // Is session active
    isActive: false,

    _isNew(cardId) {
      return ReviewStorage.getCardStats(cardId).totalReviews === 0;
    },

    _pickNext(justAnsweredId) {
      const dueRetries = this.retryQueue
        .filter(r => r.counter <= 0)
        .sort((a, b) => a.counter - b.counter);
      if (dueRetries.length > 0) {
        const retryId = dueRetries[0].cardId;
        this.retryQueue = this.retryQueue.filter(r => r.cardId !== retryId);
        const card = CardStorage.getById(retryId);
        if (card && !card.isArchived) return card;
      }

      const settings = SettingsStorage.get();
      const excludeNew = this.newCardsSurfaced >= (settings.newCardsPerSession || 0);

      const picked = Scheduler.pickNextCard(this.currentDeckId, {
        excludeCardId: justAnsweredId,
        excludeNew
      });

      if (!picked && excludeNew) {
        return Scheduler.pickNextCard(this.currentDeckId, {
          excludeCardId: justAnsweredId,
          excludeNew: false
        });
      }
      return picked;
    },

    /**
     * Start a new session
     */
    start(deckId) {
      const cards = CardStorage.getByDeck(deckId);
      if (cards.length === 0) {
        Alpine.store('app').showError('No cards in this deck. Add a deck from Settings and refresh.');
        return false;
      }

      this.currentDeckId = deckId;
      this.sessionStartedAt = Date.now();
      this.reviewedCount = 0;
      this.correctCount = 0;
      this.retryQueue = [];
      this.newCardsSurfaced = 0;
      this.isActive = true;
      this.state = 'question';
      this.nextCardData = null;

      const first = this._pickNext(null);
      if (!first) {
        Alpine.store('app').showError('No cards to review right now.');
        this.isActive = false;
        return false;
      }

      this.currentCard = first;
      if (this._isNew(first.id)) this.newCardsSurfaced++;
      this.cardStartedAt = Date.now();

      Alpine.store('app').navigate('session');
      return true;
    },

    /**
     * Flip the card to show answer
     */
    flip() {
      if (this.state === 'question') {
        this.state = 'answer';
      }
    },

    /**
     * Answer the card
     * @param {boolean} correct - Was the answer correct
     */
    answer(correct) {
      // Only accept answers when showing the answer
      if (this.state !== 'answer' || !this.currentCard) return;

      const answeredAt = Date.now();
      const durationMs = answeredAt - this.cardStartedAt;

      // Record the review
      ReviewStorage.create({
        cardId: this.currentCard.id,
        deckId: this.currentCard.deckId,
        startedAt: new Date(this.cardStartedAt).toISOString(),
        answeredAt: new Date(answeredAt).toISOString(),
        durationMs,
        outcome: correct ? 'correct' : 'incorrect'
      });

      this.reviewedCount++;
      if (correct) {
        this.correctCount++;
      }

      // Check if there are more cards
      if (this.queue.length === 0) {
        this.end();
        return;
      }

      // Preload next card data
      this.nextCardData = this.queue.shift();

      // Transition to flipping state (card flips back, but content stays)
      this.state = 'flipping';

      // After flip animation completes, swap the card content
      // (600ms matches the CSS flip animation; changing one requires the other)
      setTimeout(() => {
        this.currentCard = this.nextCardData;
        this.nextCardData = null;
        this.cardStartedAt = Date.now();
        this.state = 'question';
      }, 600);
    },

    /**
     * End the session
     */
    end() {
      this.isActive = false;
      this.currentCard = null;
      Alpine.store('app').navigate('home');

      if (this.reviewedCount > 0) {
        const rate = Math.round((this.correctCount / this.reviewedCount) * 100);
        Alpine.store('app').showSuccess(
          `Session complete! ${this.reviewedCount} cards reviewed, ${rate}% correct.`
        );
      }
    },

    /**
     * Get session progress
     */
    getProgress() {
      const total = this.reviewedCount + this.queue.length;
      if (total === 0) return 0;
      return Math.round((this.reviewedCount / total) * 100);
    }
  });

  /**
   * Stats store
   * Manages statistics display
   */
  Alpine.store('stats', {
    // Current view: 'deck' | 'card'
    view: 'deck',

    // Selected card for detail view
    selectedCard: null,

    // Deck stats cache
    deckStats: null,

    // Card stats cache
    cardStats: [],

    /**
     * Load deck statistics
     */
    loadDeckStats(deckId) {
      this.deckStats = ReviewStorage.getDeckStats(deckId);
      this.loadCardStats(deckId);
    },

    /**
     * Load per-card statistics
     */
    loadCardStats(deckId) {
      const cards = CardStorage.getByDeck(deckId);
      this.cardStats = cards.map(card => ({
        ...card,
        stats: ReviewStorage.getCardStats(card.id)
      }));

      // Sort by most needs review (lowest success rate, then by least seen)
      this.cardStats.sort((a, b) => {
        const aRate = a.stats.totalReviews > 0
          ? a.stats.correct / a.stats.totalReviews
          : 0;
        const bRate = b.stats.totalReviews > 0
          ? b.stats.correct / b.stats.totalReviews
          : 0;
        if (aRate !== bRate) return aRate - bRate;
        return a.stats.totalReviews - b.stats.totalReviews;
      });
    },

    /**
     * Select a card for detail view
     */
    selectCard(card) {
      this.selectedCard = card;
      this.view = 'card';
    },

    /**
     * Go back to deck view
     */
    backToDeck() {
      this.selectedCard = null;
      this.view = 'deck';
    }
  });

  /**
   * Settings store
   * Manages algorithm settings
   */
  Alpine.store('settings', {
    // Current settings
    values: {},

    /**
     * Load settings
     */
    load() {
      this.values = SettingsStorage.get();
    },

    /**
     * Update a setting
     */
    update(key, value) {
      this.values[key] = parseFloat(value);
      SettingsStorage.update(this.values);
    },

    /**
     * Reset to defaults
     */
    reset() {
      this.values = SettingsStorage.reset();
      Alpine.store('app').showSuccess('Settings reset to defaults');
    }
  });

  // Initialize stores
  Alpine.store('app').init();
  Alpine.store('settings').load();
});

// Scheduler is loaded from js/scheduler.js
