#!/bin/bash
# Updates version.js with git SHA and build timestamp

GIT_SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_DIRTY=$(git diff --quiet 2>/dev/null || echo "-dirty")
BUILD_TIME=$(date -u +"%Y-%m-%d %H:%M:%S UTC")

cat > version.js << EOF
// Auto-generated by update-version.sh - do not edit manually
window.APP_VERSION = '${GIT_SHA}${GIT_DIRTY}';
window.APP_GIT_SHA = '${GIT_SHA}${GIT_DIRTY}';
window.APP_BUILD_TIME = '${BUILD_TIME}';
EOF

echo "Updated version.js: ${GIT_SHA}${GIT_DIRTY} (${BUILD_TIME})"

